//HOME
export const HOME_CAROUSEL = 'HOME_CAROUSEL';
export const HOME_CAROUSEL_SUCCESS = 'HOME_CAROUSEL_SUCCESS';
export const HOME_CAROUSEL_FAILED = 'HOME_CAROUSEL_FAILED';
export const HOME_POUPALR_FRAMES = 'HOME_POUPALR_FRAMES';
export const HOME_POUPALR_FRAMES_SUCCESS = 'HOME_POUPALR_FRAMES_SUCCESS';
export const HOME_POUPALR_FRAMES_FAILED = 'HOME_POUPALR_FRAMES_FAILED';

//LIST
export const LOAD_LIST__FRAMES = 'LOAD_LIST__FRAMES';
export const LIST_FRAME_SUCCESS = 'LIST_FRAME_SUCCESS';
export const LIST_FRAME_FAILED = 'LIST_FRAME_FAILED';
export const LIST_SORT = 'LIST_SORT';
