//HOME
export const HOME_CAROUSEL = 'HOME_CAROUSEL';
export const HOME_CAROUSEL_SUCCESS = 'HOME_CAROUSEL_SUCCESS';
export const HOME_CAROUSEL_FAILED = 'HOME_CAROUSEL_FAILED';
export const HOME_POUPALR_FRAMES = 'HOME_POUPALR_FRAMES';
export const HOME_POUPALR_FRAMES_SUCCESS = 'HOME_POUPALR_FRAMES_SUCCESS';
export const HOME_POUPALR_FRAMES_FAILED = 'HOME_POUPALR_FRAMES_FAILED';
